### ISSUE TITLE
Versioning, SemVer, tags, CHANGELOG

### ISSUE THREAD

**Issue by pda** [pda/flexihash#10]
* Current version, which has barely been touched for seven years, should be tagged as `v1.0.0`.
* `CHANGELOG.md` should be created.
* Future versioning should follow [SemVer](http://semver.org/)
    * Changing autoloaders, namespacing etc should be a major release e.g. `v2.0.0`

**Comment by dmnc** [comment]
Given we already have quite a few installs from [packagist](https://packagist.org/packages/flexihash/flexihash) of 1.0.0 that comes from https://github.com/dmnc/flexihash/releases/tag/v1.0.0 and that this is API identical to the old version here (but uses composer and phpunit) could I suggest the following:

- We tag a release of current master as v0.1.0.
- What will be pulled over from dmnc/flexihash we keep as v1.0.0.
- v2.0.0 is PSR-4 compliant, namespaced, 5.4+ only etc.

I'll pop in a changelog as per http://keepachangelog.com/ in v1.0.0 before pulling it across and tagging.

I'm aware that your busy and really appreciate the help in getting this going but don't want to suck up too much of your time, so feel free to just give a nod and I'll plough ahead with this.

**Comment by pda** [comment]
Sounds perfect :+1:

**Comment by dmnc** [comment]
@pda thanks. This is all basically there. The only remaining task is to add the repo to Travis and Coveralls which requires an administrator.

If you could please either add these or, if you're happy to do so, make me a repo admin so I can do myself, that would be a great help.

**Comment by dmnc** [comment]
@pda Apologies, but a little nudge.

**Comment by dmnc** [comment]
@pda Can I nudge again please. I'd really like to connect up travis and coveralls.

**Comment by pda** [comment]
Hey, sorry for not responding earlier, life has been busy living overseas.

I believe I've enabled Travis and Coveralls — does it seem correct?

**Comment by dmnc** [comment]
No problem. I have just pushed a test PR. We shall see shortly.
