### ISSUE TITLE
Create a composer package

### ISSUE THREAD

**Issue by kornrunner** [pda/flexihash#6]
It would be great (and appreciated) if you could create a composer package for this library. Thank you!

**Comment by dmnc** [comment]
@pda Would you be willing to accept that pull request and maybe even put this on packagist?

I'd be happy to take the project over if you no longer have the time. I haven't seen another PHP consistent hasher out there.

**Comment by kerinin** [comment]
:+1:

**Comment by dmnc** [comment]
This is now on packagist at https://packagist.org/packages/flexihash/flexihash
