### ISSUE TITLE
PSR-4 autoloader

### ISSUE THREAD

**Issue by pda** [pda/flexihash#9]
Crufty SPL autoloader initialization in [`init.php`](https://github.com/pda/flexihash/blob/master/include/init.php) should be replaced with [PSR-4 Autoloader](http://www.php-fig.org/psr/psr-4/).

I guess this also implies namespacing the classes.

**Comment by dmnc** [comment]
This is sorted in the [dev-2.0 branch](https://github.com/pda/flexihash/tree/dev-2.0).
